services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zeno-net

  api:
    build:
      context: ./apps/api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URL: ${DB_URL}
      STRIPE_SECRET: ${STRIPE_SECRET}
      STRIPE_PUBLIC: ${STRIPE_PUBLIC}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URLS: ${FRONTEND_URLS}

    networks:
      - zeno-net

  web:
    build:
      context: ./apps/web
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - zeno-net

volumes:
  pgdata:

networks:
  zeno-net:
