name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Cache turbo build cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.ref }}
            turbo-

      - name: Run lint (optional, if configured)
        run: npx turbo run lint || echo "No lint step defined"

      - name: Run tests
        run: npx turbo run test

      - name: Run build
        run: npx turbo run build
